### ISSUE TITLE
CI: enforce the CGO-free and cross-platform build invariants

### ISSUE THREAD

**Issue by danieljustus** [danieljustus/symaira-corekit#193]
## Goal

Make CI actually check the two build invariants the repository documents, and close the formatting gate that was removed without a replacement.

## Why now

Surfaced by a code review on 2026-08-28 in category "Security". Estimated effort/impact: Low effort / high impact.

## Current state / Evidence

`AGENTS.md` states the hard constraint "100% CGO-free: `CGO_ENABLED=0` must work for linux/darwin/windows (amd64+arm64)", and the README repeats the CGO-free promise. Neither half is verified:

- `.github/workflows/ci.yml:14` builds and tests on `ubuntu-latest` and `macos-latest` only, with the default `CGO_ENABLED`, and has no cross-build step. The `Makefile` sets `CGO_ENABLED=0`, but CI does not use those targets.
- Windows is never compiled. `GOOS=windows go vet ./fsutil/` fails today at `fsutil/safewrite_test_additions_test.go:58` with `undefined: syscall.Mkfifo`, so the `fsutil` test package cannot build on a platform the README advertises as supported. `fsutil/safewrite_windows.go` is likewise never compiled or vetted.

Verified locally: `CGO_ENABLED=0 go build ./...`, `GOOS=windows GOARCH=amd64 go build ./...` and `GOOS=linux GOARCH=arm64 go build ./...` all pass, and `CGO_ENABLED=0 go test -race ./...` works on Go 1.26 — so enabling these checks should not require code changes beyond the Mkfifo build tag.

A third, separate gap in the same workflow: the `lint` job invokes `golangci/golangci-lint-action` twice (`.github/workflows/ci.yml:39` labelled "Install", `:41` labelled "Run"), so the linter runs twice. The `gofmt -l` / `go vet` steps that were commented out at `.github/workflows/ci.yml:43` are annotated as "replaced by golangci-lint above", but `.golangci.yml` sets `default: none` and enables only `gosec` and `govet` — formatting is not among them. Formatting is therefore only checked in `.github/workflows/release.yml:44`, i.e. after merge.

References:
- `.github/workflows/ci.yml:14`
- `.github/workflows/ci.yml:39`
- `.github/workflows/ci.yml:43`
- `.golangci.yml`
- `fsutil/safewrite_test_additions_test.go:58`
- `fsutil/safewrite_windows.go`

## In Scope

- Setting `CGO_ENABLED=0` on the CI build and test steps.
- A cross-build matrix step running `go build ./...` and `go vet ./...` over linux/darwin/windows × amd64/arm64.
- Guarding the Mkfifo-based test with a `//go:build !windows` tag so `fsutil` builds on Windows.
- Removing the duplicate `golangci-lint-action` invocation.
- Restoring a formatting gate by enabling `gofmt` (and `staticcheck`) in `.golangci.yml`.

## Out of Scope

- Adding Windows to the test-execution matrix (build and vet coverage is the goal here; running the suite on Windows is a separate decision).
- Changing the release workflow's own gates.
- Broad linter adoption beyond `gofmt`/`staticcheck`.

## Acceptance criteria

- [ ] CI builds and tests with `CGO_ENABLED=0`.
- [ ] CI cross-builds and vets linux, darwin and windows for both amd64 and arm64, and fails if any combination breaks.
- [ ] `GOOS=windows go vet ./...` passes, including test files.
- [ ] The `lint` job runs `golangci-lint` exactly once.
- [ ] A `gofmt` violation fails CI on a pull request, not only at release time.
- [ ] Existing tests continue to pass.

## Source

Review file: `.github/review/2026-08-28T12-02-43Z.md`
HEAD at review: `25f808608303e255e5bf9c2f08eb4bacfa43245d`
